# Generated by Django 5.0.14 on 2026-07-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
