# Generated by Django 5.0.14 on 2026-07-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0002_kegiatan_latitude_kegiatan_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='catatan_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='disetujui', max_length=20),
        ),
    ]
