# Generated by Django 5.0.14 on 2026-07-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0003_kegiatan_catatan_admin_kegiatan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
