# Generated by Django 6.0.6 on 2026-07-09 01:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('pptk', 'PPTK'), ('pimpinan', 'Pimpinan')], default='pptk', max_length=20)),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('unit_kerja', models.CharField(blank=True, max_length=100)),
                ('status_aktif', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_kegiatan', models.CharField(max_length=255)),
                ('tahun', models.IntegerField(default=2026)),
                ('pptk', models.ForeignKey(limit_choices_to={'role': 'pptk'}, on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Kegiatan',
            },
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan_laporan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=20)),
                ('tahapan_pelaksanaan', models.TextField()),
                ('kendala', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Diajukan'), ('terverifikasi', 'Terverifikasi'), ('perlu_revisi', 'Perlu Revisi')], default='draft', max_length=20)),
                ('catatan_revisi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='pelaporan.kegiatan')),
                ('pptk', models.ForeignKey(limit_choices_to={'role': 'pptk'}, on_delete=django.db.models.deletion.CASCADE, related_name='laporan_pptk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laporan',
                'verbose_name_plural': 'Laporan',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Dokumentasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dokumentasi/')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumentasi', to='pelaporan.laporan')),
            ],
            options={
                'verbose_name': 'Dokumentasi',
                'verbose_name_plural': 'Dokumentasi',
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pelaporan.laporan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_lama', models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Diajukan'), ('terverifikasi', 'Terverifikasi'), ('perlu_revisi', 'Perlu Revisi')], max_length=20)),
                ('status_baru', models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Diajukan'), ('terverifikasi', 'Terverifikasi'), ('perlu_revisi', 'Perlu Revisi')], max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_status', to='pelaporan.laporan')),
            ],
            options={
                'verbose_name': 'Riwayat Status',
                'verbose_name_plural': 'Riwayat Status',
                'ordering': ['-created_at'],
            },
        ),
    ]
